spring:
  application:
    name: spring-with-openapi
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
server:
  port: 8080
management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin/actuator

resilience4j.ratelimiter.instances.apiLimiter:
  limit-for-period: 10
  limit-refresh-period: 1s
  timeout-duration: 0

resilience4j.circuitbreaker.instances.apiCB:
  failure-rate-threshold: 50
  wait-duration-in-open-state: 5s
  sliding-window-size: 10
  sliding-window-type: count_based