spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hw_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"