spring:
  application:
    name: spring-with-openapi
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
server:
  port: 8080
management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin/actuator
